version: "3.3"

services:
  db:
    container_name: db
    image: postgres:11.13
    environment:
      - POSTGRES_USER=bandrw
      - POSTGRES_PASSWORD=bandrw
      - POSTGRES_DB=bandrw
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    command: postgres -c stats_temp_directory=/tmp

  server:
    container_name: server
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:3000"
